<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright © 2021 Christopher Kujawa (zelldon91@gmail.com)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.zell</groupId>
    <artifactId>zdb</artifactId>
    <version>2.7.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>ZDB</name>
    <inceptionYear>2021</inceptionYear>
    <url>https://github.com/ChrisKujawa/zdb</url>

    <licenses>
        <license>
            <name>Apache 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <organization>
        <name>Christopher Kujawa</name>
        <url>https://github.com/ChrisKujawa</url>
    </organization>
    <properties>
        <bom.version.assertj>3.27.7</bom.version.assertj>
        <bom.version.junit>6.1.3</bom.version.junit>
        <bom.version.kotlin>2.4.20</bom.version.kotlin>
        <bom.version.slf4j>2.0.19</bom.version.slf4j>
        <bom.version.testcontainers>1.21.4</bom.version.testcontainers>
        <bom.version.zeebe>8.9.19</bom.version.zeebe>
        <java-diff-utils.version>4.17</java-diff-utils.version>
        <exec-maven-plugin.version>1.6.0</exec-maven-plugin.version>
        <jackson-databind.version>2.13.0</jackson-databind.version>
        <javafx.version>25.0.4</javafx.version>
        <kotlin-maven-plugin.version>1.4.32</kotlin-maven-plugin.version>
        <kotlin-stdlib-jdk8.version>1.4.10</kotlin-stdlib-jdk8.version>
        <kotlin-test-junit5.version>1.4.10</kotlin-test-junit5.version>
        <kotlin.code.style>official</kotlin.code.style>
        <kotlin.compiler.jvmTarget>21</kotlin.compiler.jvmTarget>
        <kotlin.serialization.version>1.11.0</kotlin.serialization.version>
        <maven-assembly-plugin.version>3.8.0</maven-assembly-plugin.version>
        <maven-compiler-plugin.version>3.16.0</maven-compiler-plugin.version>
        <maven-failsafe-plugin.version>2.22.2</maven-failsafe-plugin.version>
        <maven-surefire-plugin.version>3.5.6</maven-surefire-plugin.version>
        <maven.compiler.release>21</maven.compiler.release>
        <plugin.version.checkstyle>3.6.0</plugin.version.checkstyle>
        <plugin.version.fmt>2.29</plugin.version.fmt>
        <plugin.version.license>5.1.2</plugin.version.license>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
        <sonar.organization>zelldon-github</sonar.organization>
        <testcontainers.version>1.21.3</testcontainers.version>
        <version.awaitility>4.3.0</version.awaitility>
        <version.guava>30.0-jre</version.guava>
        <version.jackson-dataformat-msgpack>0.8.21</version.jackson-dataformat-msgpack>
        <version.jackson>2.13.0</version.jackson>
        <version.jib>3.5.2</version.jib>
        <version.kryo>4.0.2</version.kryo>
        <version.log4j>2.14.1</version.log4j>
        <version.picocli>4.7.7</version.picocli>
        <zeebe-test-container.version>3.6.9</zeebe-test-container.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-bom</artifactId>
                <version>${bom.version.kotlin}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>io.camunda</groupId>
                <artifactId>zeebe-bom</artifactId>
                <version>${bom.version.zeebe}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${bom.version.junit}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-bom</artifactId>
                <version>${bom.version.assertj}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>${bom.version.testcontainers}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-bom</artifactId>
                <version>${bom.version.slf4j}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>


            <dependency>
                <groupId>info.picocli</groupId>
                <artifactId>picocli</artifactId>
                <version>${version.picocli}</version>
            </dependency>


            <dependency>
                <groupId>io.zell</groupId>
                <artifactId>backend</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-controls</artifactId>
                <version>${javafx.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-fxml</artifactId>
                <version>${javafx.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>backend</module>
        <module>cli</module>
        <module>frontend</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>${version.jib}</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${version.jib}</version>
                <executions>
                    <execution>
                        <phase>deploy</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <to>
                        <image>ghcr.io/chriskujawa/zdb</image>
                        <tags>${project.version}</tags>
                    </to>
                    <container>
                        <mainClass>io.zell.zdb.ZeebeDebugger</mainClass>
                    </container>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>${plugin.version.license}</version>
                <configuration>
                    <properties>
                        <owner>Christopher Kujawa</owner>
                        <email>zelldon91@gmail.com</email>
                    </properties>
                    <licenseSets>
                        <licenseSet>
                            <header>com/mycila/maven/plugin/license/templates/APACHE-2.txt</header>
                            <includes>
                                <include>**/*.java</include>
                                <include>**/*.kt</include>
                            </includes>
                            <excludes>
                                <exclude>licenses/*.txt</exclude>
                            </excludes>
                        </licenseSet>
                    </licenseSets>
                    <mapping>
                        <java>SLASHSTAR_STYLE</java>
                    </mapping>
                    <!--
                       Will only add license headers if file has none, to only add our copyright
                       to new added files. We need to make sure that the old ONF copyrights are saved
                       and not replaced accidentally.
                    -->
                    <skipExistingHeaders>true</skipExistingHeaders>
                </configuration>
                <executions>
                    <execution>
                        <id>add-license</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
