# This workflow will build and push the zdb docker image when a release is created
name: Deploy docker image on release

on:
  release:
    types: [ published ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4.3.0
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker image with Maven
      run: mvn -B package jib:build -DskipTests
